### ISSUE TITLE
Roadmap + Design proposal 

### ISSUE THREAD

**Issue by quangIO** [nyu-ossd-s20/fontChanger#2]
* [x] System fonts detection
* [ ] Support web fonts
* [ ] Preview fonts
* [ ] Select font for individual tags
* [ ] Persistent changes
* [ ] Change font
  * [x] Naive solution: traverse all dom elements
  * [ ] Leveraging CSS selector: perhaps we can make a better heuristic here as internal CSS engine will be multi-threaded soon; JavaScript engine will not.

If anyone want to do any of those things, please create a new separate issue.
